name: CustomVehicles
version: '${version}'

main: org.rexi.customVehicles.CustomVehicles
api-version: '1.21.4'
load: POSTWORLD

commands:
  vehicle:
    description: Gestiona los vehículos personalizados
    usage: /vehicle <spawn|list|reload>
    aliases:
      - vehicles
      - car

permissions:
  customvehicles.admin.reload:
    description: Permite recargar las definiciones de vehículos
    default: op